cc_library(
    name = "future",
    srcs = glob([
        "*.cpp",
    ]),
    hdrs = glob([
        "*.hpp",
    ]),
    includes = [
        ".",
    ],
    deps = [
        "@concurrentqueue//:concurrentqueue",
    ],
    visibility = ["//visibility:public"],
)
