cc_library(
    name = "coroutine",
    srcs = glob([
        "*.cpp",
    ]),
    hdrs = glob([
        "*.hpp",
    ]),
    includes = [
        ".",
    ],
    deps = [
        "//future:future",
    ],
    visibility = ["//visibility:public"],
)

#cc_binary(
#    name = "fibonacci",
#    srcs = glob([
#        "example/fibonacci.*",
#    ]),
#    includes = [
#        "example/",
#    ],
#)
